version: "3.4"

services:
  ib-api-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      SERVER_PORT: 3000
      TWS_USERID: ${TWS_USERID}
      TWS_PASSWORD: ${TWS_PASSWORD}
      TRADING_MODE: ${TRADING_MODE:-live}
    ports:
      - "5900:5900"
      - "3002:3000"
