version: "3.4"

services:
  ib-api-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      SERVER_PORT: 3000
      REST_API_USERNAME: ${TWS_USERID}
      REST_API_PASSWORD: ${TWS_PASSWORD}
      TWS_USERID: ${TWS_USERID}
      TWS_PASSWORD: ${TWS_PASSWORD}
      TRADING_MODE: ${TRADING_MODE:-live}
      VNC_SERVER_PASSWORD: ${VNC_SERVER_PASSWORD:-}
    ports:
      - "3000:3000"
      - "5900:5900"
